/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module display_red_16 (
    input clk,
    input rst,
    input [63:0] red,
    output reg [7:0] r_red,
    output reg [7:0] c_red
  );
  
  
  
  localparam FLIP = 5'h10;
  
  wire [3-1:0] M_counter_r_value;
  counter_27 counter_r (
    .clk(clk),
    .rst(rst),
    .value(M_counter_r_value)
  );
  
  reg [4:0] whichrow;
  
  integer i;
  
  always @* begin
    r_red = 8'hff;
    c_red = 8'hff;
    whichrow = M_counter_r_value;
    r_red[(whichrow)*1+0-:1] = 1'h0;
    for (i = 1'h0; i < 4'h8; i = i + 1) begin
      c_red[(i)*1+0-:1] = red[(whichrow)*8+(i)*1+0-:1];
    end
  end
endmodule
