/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_20 (
    input [7:0] a_shift,
    input [2:0] b_shift,
    input [1:0] alufn,
    output reg [7:0] shift_out
  );
  
  
  
  always @* begin
    shift_out = a_shift;
    if (alufn[0+0-:1] == 1'h0 & alufn[1+0-:1] == 1'h0) begin
      shift_out = a_shift << b_shift[0+2-:3];
    end
    if (alufn[0+0-:1] == 1'h1 & alufn[1+0-:1] == 1'h0) begin
      shift_out = a_shift >> b_shift[0+2-:3];
    end
    if (alufn[0+0-:1] == 1'h1 & alufn[1+0-:1] == 1'h1) begin
      shift_out = $signed(a_shift) >>> b_shift[0+2-:3];
    end
  end
endmodule
